spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_network
    password: postgres
    username: postgres
security:
  enabled: true
#  if security is disabled then principal with username will be created
  principalUsername: maxkizi