spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_network
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: db/liquibase-changelog.xml