insert into users(first_name, last_name, country, is_followed, status, info, photo_url)
values ('Maxim', 'Kizilov', 'Russia', true, 'Яхай', 'Заработчик',
        'https://sun9-83.userapi.com/impf/c848416/v848416721/123dc5/NsMh-Qe3wQU.jpg?size=1280x1280&quality=96&sign=23c7396d0f6d4adb42863e671aed4f20&type=album'),
       ('Annastasia', 'Kush', 'Russia', true, 'Это прикол', 'Настя',
        'https://sun9-14.userapi.com/impf/c849324/v849324556/f4b5c/M1yEwzicINQ.jpg?size=1080x1350&quality=96&sign=5ab6250119e4bc9c34372085a0d3c2a9&type=album'),
       ('Anna', 'Ivanova', 'Russia', false, null, null, null),
       ('Nastya', 'Smirnova', 'Russia', false, null, null, null),
       ('Alexander', 'Alexandrov', 'Russia', false, null, null, null),
       ('Alex', 'Sidorov', 'Belarus', false, null, null, null),
       ('Nataly', 'Ivanova', 'Belarus', false, null, null, null),
       ('Elena', 'Sidorenko', 'Belarus', false, null, null, null),
       ('Ivan', 'Medved', 'Belarus', false, null, null, null),
       ('Sergey', 'Kazakov', 'Ukraine', false, null, null, null),
       ('Yuli', 'Pavlova', 'Ukraine', false, null, null, null),
       ('Dima', 'Smirnov', 'Ukraine', false, null, null, null),
       ('Varvara', 'Lubnina', 'Ukraine', false, null, null, null),
       ('Mary', 'Lubnina', 'Ukraine', false, null, null, null),
       ('Nick', 'Doe', 'USA', false, null, null, null),
       ('John', 'Johnson', 'USA', false, null, null, null),
       ('Max', 'Kim', 'USA', false, null, null, null),
       ('Liza', 'Vasilkova', 'USA', false, null, null, null),
       ('Jack', 'Jackson', 'USA', false, null, null, null),
       ('Dean', 'Winchester', 'USA', false, null, null, null),
       ('Sam', 'Winchester', 'USA', false, null, null, null),
       ('Kurt', 'Cobain', 'USA', false, null, null, null);